import 'models.dart';

const kBroSplitProgram = Program(
  id: 'bro-split-v1',
  name: '5-day bro split + compound maintenance',
  weeks: 8,
  schedulePattern: ['day-1', 'day-2', 'day-3', 'day-4', 'day-5'],
  workouts: [
    Workout(
      id: 'day-1',
      name: 'Day 1 - Chest + Triceps',
      blocks: [
        ExerciseBlock(
          id: 'day-1-bench-press',
          exerciseId: 'bench-press',
          minSets: 2,
          maxSets: 2,
          repMin: 4,
          repMax: 6,
          restMinSeconds: 120,
          restMaxSeconds: 180,
        ),
        ExerciseBlock(
          id: 'day-1-incline-machine-press',
          exerciseId: 'incline-machine-press',
          minSets: 2,
          maxSets: 2,
          repMin: 8,
          repMax: 12,
          restMinSeconds: 90,
          restMaxSeconds: 90,
        ),
        ExerciseBlock(
          id: 'day-1-pec-deck-cable-fly',
          exerciseId: 'pec-deck-cable-fly',
          minSets: 2,
          maxSets: 2,
          repMin: 12,
          repMax: 20,
          restMinSeconds: 60,
          restMaxSeconds: 90,
        ),
        ExerciseBlock(
          id: 'day-1-triceps-pressdown',
          exerciseId: 'triceps-pressdown',
          minSets: 2,
          maxSets: 2,
          repMin: 10,
          repMax: 15,
          restMinSeconds: 60,
          restMaxSeconds: 90,
        ),
      ],
    ),
    Workout(
      id: 'day-2',
      name: 'Day 2 - Back + Biceps',
      blocks: [
        ExerciseBlock(
          id: 'day-2-row',
          exerciseId: 'row',
          minSets: 2,
          maxSets: 2,
          repMin: 6,
          repMax: 8,
          restMinSeconds: 120,
          restMaxSeconds: 120,
          equipmentHint: 'Use straps if grip limits back work.',
        ),
        ExerciseBlock(
          id: 'day-2-neutral-grip-lat-pulldown',
          exerciseId: 'neutral-grip-lat-pulldown',
          minSets: 3,
          maxSets: 3,
          repMin: 8,
          repMax: 12,
          restMinSeconds: 90,
          restMaxSeconds: 90,
          equipmentHint: 'Use straps if grip limits back work.',
        ),
        ExerciseBlock(
          id: 'day-2-cable-row',
          exerciseId: 'cable-row',
          minSets: 2,
          maxSets: 2,
          repMin: 10,
          repMax: 15,
          restMinSeconds: 90,
          restMaxSeconds: 90,
          equipmentHint: 'Use straps if grip limits back work.',
        ),
        ExerciseBlock(
          id: 'day-2-reverse-pec-deck',
          exerciseId: 'reverse-pec-deck',
          minSets: 2,
          maxSets: 2,
          repMin: 15,
          repMax: 25,
          restMinSeconds: 60,
          restMaxSeconds: 60,
        ),
        ExerciseBlock(
          id: 'day-2-cable-curl',
          exerciseId: 'cable-curl',
          minSets: 2,
          maxSets: 2,
          repMin: 10,
          repMax: 15,
          restMinSeconds: 60,
          restMaxSeconds: 90,
        ),
      ],
    ),
    Workout(
      id: 'day-3',
      name: 'Day 3 - Legs',
      blocks: [
        ExerciseBlock(
          id: 'day-3-squat',
          exerciseId: 'squat',
          minSets: 2,
          maxSets: 2,
          repMin: 4,
          repMax: 6,
          restMinSeconds: 120,
          restMaxSeconds: 180,
        ),
        ExerciseBlock(
          id: 'day-3-leg-press-hack-squat',
          exerciseId: 'leg-press-hack-squat',
          minSets: 2,
          maxSets: 2,
          repMin: 8,
          repMax: 12,
          restMinSeconds: 90,
          restMaxSeconds: 120,
        ),
        ExerciseBlock(
          id: 'day-3-leg-extension',
          exerciseId: 'leg-extension',
          minSets: 2,
          maxSets: 2,
          repMin: 12,
          repMax: 20,
          restMinSeconds: 60,
          restMaxSeconds: 90,
        ),
        ExerciseBlock(
          id: 'day-3-leg-curl',
          exerciseId: 'leg-curl',
          minSets: 3,
          maxSets: 3,
          repMin: 10,
          repMax: 15,
          restMinSeconds: 60,
          restMaxSeconds: 90,
        ),
        ExerciseBlock(
          id: 'day-3-calf-raise',
          exerciseId: 'calf-raise',
          minSets: 2,
          maxSets: 2,
          repMin: 8,
          repMax: 15,
          restMinSeconds: 60,
          restMaxSeconds: 90,
        ),
      ],
    ),
    Workout(
      id: 'day-4',
      name: 'Day 4 - Shoulders + chest/back top-up',
      blocks: [
        ExerciseBlock(
          id: 'day-4-overhead-press',
          exerciseId: 'overhead-press',
          minSets: 2,
          maxSets: 2,
          repMin: 4,
          repMax: 6,
          restMinSeconds: 120,
          restMaxSeconds: 180,
        ),
        ExerciseBlock(
          id: 'day-4-cable-lateral-raise',
          exerciseId: 'cable-lateral-raise',
          minSets: 3,
          maxSets: 3,
          repMin: 12,
          repMax: 20,
          restMinSeconds: 60,
          restMaxSeconds: 90,
        ),
        ExerciseBlock(
          id: 'day-4-reverse-pec-deck',
          exerciseId: 'reverse-pec-deck',
          minSets: 2,
          maxSets: 2,
          repMin: 15,
          repMax: 25,
          restMinSeconds: 60,
          restMaxSeconds: 60,
        ),
        ExerciseBlock(
          id: 'day-4-incline-machine-press-push-up',
          exerciseId: 'incline-machine-press-push-up',
          minSets: 2,
          maxSets: 2,
          repMin: 10,
          repMax: 15,
          restMinSeconds: 90,
          restMaxSeconds: 90,
        ),
        ExerciseBlock(
          id: 'day-4-pulldown-cable-row',
          exerciseId: 'pulldown-cable-row',
          minSets: 2,
          maxSets: 2,
          repMin: 10,
          repMax: 15,
          restMinSeconds: 90,
          restMaxSeconds: 90,
        ),
      ],
    ),
    Workout(
      id: 'day-5',
      name: 'Day 5 - Arms + posterior chain',
      blocks: [
        ExerciseBlock(
          id: 'day-5-romanian-deadlift',
          exerciseId: 'romanian-deadlift',
          minSets: 2,
          maxSets: 2,
          repMin: 6,
          repMax: 8,
          restMinSeconds: 120,
          restMaxSeconds: 180,
        ),
        ExerciseBlock(
          id: 'day-5-triceps-pressdown',
          exerciseId: 'triceps-pressdown',
          minSets: 3,
          maxSets: 3,
          repMin: 10,
          repMax: 15,
          restMinSeconds: 60,
          restMaxSeconds: 90,
        ),
        ExerciseBlock(
          id: 'day-5-overhead-triceps-extension',
          exerciseId: 'overhead-triceps-extension',
          minSets: 2,
          maxSets: 2,
          repMin: 12,
          repMax: 20,
          restMinSeconds: 60,
          restMaxSeconds: 90,
        ),
        ExerciseBlock(
          id: 'day-5-preacher-curl',
          exerciseId: 'preacher-curl',
          minSets: 3,
          maxSets: 3,
          repMin: 8,
          repMax: 12,
          restMinSeconds: 60,
          restMaxSeconds: 90,
        ),
        ExerciseBlock(
          id: 'day-5-incline-curl-cable-curl',
          exerciseId: 'incline-curl-cable-curl',
          minSets: 2,
          maxSets: 2,
          repMin: 10,
          repMax: 15,
          restMinSeconds: 60,
          restMaxSeconds: 90,
        ),
        ExerciseBlock(
          id: 'day-5-optional-abs',
          exerciseId: 'optional-abs',
          minSets: 2,
          maxSets: 2,
          repMin: 10,
          repMax: 20,
          restMinSeconds: 60,
          restMaxSeconds: 60,
        ),
      ],
    ),
  ],
  exercises: [
    Exercise(
      id: 'bench-press',
      name: 'Bench press',
      category: ExerciseCategory.push,
      defaultIncrementKg: 2.5,
      smallestPlatePairKg: 2.5,
      isBarbell: true,
    ),
    Exercise(
      id: 'incline-machine-press',
      name: 'Incline machine press',
      category: ExerciseCategory.push,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'pec-deck-cable-fly',
      name: 'Pec deck / cable fly',
      category: ExerciseCategory.push,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'triceps-pressdown',
      name: 'Triceps pressdown',
      category: ExerciseCategory.arms,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'row',
      name: 'Chest-supported row / barbell row',
      category: ExerciseCategory.pull,
      defaultIncrementKg: 2.5,
      smallestPlatePairKg: 2.5,
      isBarbell: true,
    ),
    Exercise(
      id: 'neutral-grip-lat-pulldown',
      name: 'Neutral-grip lat pulldown',
      category: ExerciseCategory.pull,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'cable-row',
      name: 'Cable row',
      category: ExerciseCategory.pull,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'reverse-pec-deck',
      name: 'Reverse pec deck',
      category: ExerciseCategory.shoulders,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'cable-curl',
      name: 'Cable curl',
      category: ExerciseCategory.arms,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'squat',
      name: 'Squat',
      category: ExerciseCategory.legs,
      defaultIncrementKg: 2.5,
      smallestPlatePairKg: 2.5,
      isBarbell: true,
    ),
    Exercise(
      id: 'leg-press-hack-squat',
      name: 'Leg press / hack squat',
      category: ExerciseCategory.legs,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'leg-extension',
      name: 'Leg extension',
      category: ExerciseCategory.legs,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'leg-curl',
      name: 'Leg curl',
      category: ExerciseCategory.legs,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'calf-raise',
      name: 'Calf raise',
      category: ExerciseCategory.calves,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'overhead-press',
      name: 'Overhead press',
      category: ExerciseCategory.shoulders,
      defaultIncrementKg: 1.25,
      smallestPlatePairKg: 1.25,
      isBarbell: true,
    ),
    Exercise(
      id: 'cable-lateral-raise',
      name: 'Cable lateral raise',
      category: ExerciseCategory.shoulders,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'incline-machine-press-push-up',
      name: 'Incline machine press / push-up',
      category: ExerciseCategory.push,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'pulldown-cable-row',
      name: 'Pulldown / cable row',
      category: ExerciseCategory.pull,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'romanian-deadlift',
      name: 'Romanian deadlift',
      category: ExerciseCategory.hinge,
      defaultIncrementKg: 2.5,
      smallestPlatePairKg: 2.5,
      isBarbell: true,
    ),
    Exercise(
      id: 'overhead-triceps-extension',
      name: 'Overhead triceps extension',
      category: ExerciseCategory.arms,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'preacher-curl',
      name: 'Preacher curl',
      category: ExerciseCategory.arms,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'incline-curl-cable-curl',
      name: 'Incline curl / cable curl',
      category: ExerciseCategory.arms,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'optional-abs',
      name: 'Optional abs',
      category: ExerciseCategory.core,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
  ],
);
