import 'models.dart';

const kReducedProgram = Program(
  id: 'reduced-v1',
  name: 'Galpin × Henselmans — Reduced',
  weeks: 8,
  schedulePattern: ['A', 'B', 'A', 'B'],
  workouts: [
    Workout(
      id: 'workout-a',
      name: 'Workout A',
      blocks: [
        ExerciseBlock(
          id: 'workout-a-romanian-deadlift',
          exerciseId: 'romanian-deadlift',
          minSets: 3,
          maxSets: 3,
          repMin: 8,
          repMax: 12,
          restMinSeconds: 150,
          restMaxSeconds: 180,
        ),
        ExerciseBlock(
          id: 'workout-a-leg-extension',
          exerciseId: 'leg-extension',
          minSets: 3,
          maxSets: 3,
          repMin: 8,
          repMax: 12,
          restMinSeconds: 120,
          restMaxSeconds: 180,
        ),
        ExerciseBlock(
          id: 'workout-a-barbell-bench-press',
          exerciseId: 'barbell-bench-press',
          minSets: 3,
          maxSets: 3,
          repMin: 6,
          repMax: 10,
          restMinSeconds: 150,
          restMaxSeconds: 180,
        ),
        ExerciseBlock(
          id: 'workout-a-neutral-grip-pulldown',
          exerciseId: 'neutral-grip-pulldown',
          minSets: 3,
          maxSets: 3,
          repMin: 8,
          repMax: 12,
          restMinSeconds: 120,
          restMaxSeconds: 180,
        ),
        ExerciseBlock(
          id: 'workout-a-seated-calf-raise',
          exerciseId: 'seated-calf-raise',
          minSets: 2,
          maxSets: 3,
          repMin: 8,
          repMax: 12,
          restMinSeconds: 90,
          restMaxSeconds: 120,
        ),
        ExerciseBlock(
          id: 'workout-a-cable-lateral-raise',
          exerciseId: 'cable-lateral-raise',
          minSets: 2,
          maxSets: 2,
          repMin: 8,
          repMax: 12,
          restMinSeconds: 90,
          restMaxSeconds: 120,
        ),
      ],
    ),
    Workout(
      id: 'workout-b',
      name: 'Workout B',
      blocks: [
        ExerciseBlock(
          id: 'workout-b-high-bar-squat',
          exerciseId: 'high-bar-squat',
          minSets: 3,
          maxSets: 3,
          repMin: 5,
          repMax: 8,
          restMinSeconds: 180,
          restMaxSeconds: 180,
        ),
        ExerciseBlock(
          id: 'workout-b-lying-leg-curl',
          exerciseId: 'lying-leg-curl',
          minSets: 3,
          maxSets: 3,
          repMin: 8,
          repMax: 12,
          restMinSeconds: 120,
          restMaxSeconds: 180,
        ),
        ExerciseBlock(
          id: 'workout-b-barbell-overhead-press',
          exerciseId: 'barbell-overhead-press',
          minSets: 3,
          maxSets: 3,
          repMin: 6,
          repMax: 10,
          restMinSeconds: 150,
          restMaxSeconds: 180,
        ),
        ExerciseBlock(
          id: 'workout-b-seated-row',
          exerciseId: 'seated-row',
          minSets: 3,
          maxSets: 3,
          repMin: 8,
          repMax: 12,
          restMinSeconds: 120,
          restMaxSeconds: 180,
        ),
        ExerciseBlock(
          id: 'workout-b-cable-chest-fly',
          exerciseId: 'cable-chest-fly',
          minSets: 3,
          maxSets: 3,
          repMin: 6,
          repMax: 10,
          restMinSeconds: 90,
          restMaxSeconds: 150,
        ),
        ExerciseBlock(
          id: 'workout-b-triceps-pushdown',
          exerciseId: 'triceps-pushdown',
          minSets: 2,
          maxSets: 2,
          repMin: 8,
          repMax: 12,
          restMinSeconds: 90,
          restMaxSeconds: 120,
        ),
        ExerciseBlock(
          id: 'workout-b-seated-dumbbell-curl',
          exerciseId: 'seated-dumbbell-curl',
          minSets: 2,
          maxSets: 2,
          repMin: 8,
          repMax: 12,
          restMinSeconds: 90,
          restMaxSeconds: 120,
        ),
      ],
    ),
  ],
  exercises: [
    Exercise(
      id: 'romanian-deadlift',
      name: 'Romanian deadlift',
      category: ExerciseCategory.legs,
      defaultIncrementKg: 2.5,
      smallestPlatePairKg: 2.5,
      isBarbell: true,
    ),
    Exercise(
      id: 'leg-extension',
      name: 'Leg extension',
      category: ExerciseCategory.legs,
      defaultIncrementKg: 2.5,
      smallestPlatePairKg: 2.5,
      isBarbell: false,
    ),
    Exercise(
      id: 'barbell-bench-press',
      name: 'Barbell bench press',
      category: ExerciseCategory.push,
      defaultIncrementKg: 2.5,
      smallestPlatePairKg: 2.5,
      isBarbell: true,
    ),
    Exercise(
      id: 'neutral-grip-pulldown',
      name: 'Neutral-grip pulldown',
      category: ExerciseCategory.pull,
      defaultIncrementKg: 2.5,
      smallestPlatePairKg: 2.5,
      isBarbell: false,
    ),
    Exercise(
      id: 'seated-calf-raise',
      name: 'Seated calf raise',
      category: ExerciseCategory.calves,
      defaultIncrementKg: 2.5,
      smallestPlatePairKg: 2.5,
      isBarbell: false,
    ),
    Exercise(
      id: 'cable-lateral-raise',
      name: 'Cable lateral raise',
      category: ExerciseCategory.shoulders,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'high-bar-squat',
      name: 'High-bar squat',
      category: ExerciseCategory.legs,
      defaultIncrementKg: 2.5,
      smallestPlatePairKg: 2.5,
      isBarbell: true,
    ),
    Exercise(
      id: 'lying-leg-curl',
      name: 'Lying leg curl',
      category: ExerciseCategory.legs,
      defaultIncrementKg: 2.5,
      smallestPlatePairKg: 2.5,
      isBarbell: false,
    ),
    Exercise(
      id: 'barbell-overhead-press',
      name: 'Barbell overhead press',
      category: ExerciseCategory.push,
      defaultIncrementKg: 2.5,
      smallestPlatePairKg: 2.5,
      isBarbell: true,
    ),
    Exercise(
      id: 'seated-row',
      name: 'Seated row',
      category: ExerciseCategory.pull,
      defaultIncrementKg: 2.5,
      smallestPlatePairKg: 2.5,
      isBarbell: false,
    ),
    Exercise(
      id: 'cable-chest-fly',
      name: 'Cable chest fly / pec deck',
      category: ExerciseCategory.push,
      defaultIncrementKg: 2.5,
      smallestPlatePairKg: 2.5,
      isBarbell: false,
    ),
    Exercise(
      id: 'triceps-pushdown',
      name: 'Triceps pushdown',
      category: ExerciseCategory.arms,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
    Exercise(
      id: 'seated-dumbbell-curl',
      name: 'Seated dumbbell curl',
      category: ExerciseCategory.arms,
      defaultIncrementKg: 1.0,
      smallestPlatePairKg: 1.0,
      isBarbell: false,
    ),
  ],
);
